#!/bin/bash
# Whisperrr Environment Variables
# Generated by setup-env.sh on Sat Dec  6 00:05:29 EST 2025
# Source this file to set environment variables: source .env-export.sh

export REACT_APP_API_URL="http://100.76.98.121:7331/api"
export WHISPERRR_SERVICE_URL="http://100.76.98.121:5001"
export CORS_ALLOWED_ORIGINS="http://whisperrr.shangmin.me:3737"
export CORS_ORIGINS="http://whisperrr.shangmin.me:3737,http://100.76.98.121:7331"

echo "Environment variables loaded from .env-export.sh"
echo "  REACT_APP_API_URL=http://100.76.98.121:7331/api"
echo "  WHISPERRR_SERVICE_URL=http://100.76.98.121:5001"
echo "  CORS_ALLOWED_ORIGINS=http://whisperrr.shangmin.me:3737"
echo "  CORS_ORIGINS=http://whisperrr.shangmin.me:3737,http://100.76.98.121:7331"
